 language: android
 sudo: required
 jdk:
   - oraclejdk8
 before_install:
   - chmod +x gradlew
   - yes | sdkmanager "platforms;android-27"
 
 env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
   - ANDROID_ABI=armeabi-v7a
   - ANDROID_TAG=google_apis
   - ADB_INSTALL_TIMEOUT=20 # minutes
 android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository
    - tools

    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL

 licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
 before_script:
    - echo no | android create avd --force -n test -t "android-$EMULATOR_API_LEVEL" --abi $ANDROID_ABI --tag $ANDROID_TAG
    - emulator -avd test -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
